-- ==============================================================================
-- import_marketing_leads.sql
-- Real leads from the Marketing Outreach database (152 businesses).
-- Run ONCE after the migrations (13, 15 to 22). Safe to re-run: skips any business
-- whose name or phone is already in the system.
--
-- Every lead starts as "Needs review" with no messages. Approve them in the review
-- queue (or with approve_import) to create platform threads, assign a salesperson
-- and draft the first message.
--
-- Services: cafés, salons, barbers and trades are pitched Website.
--           Hotels are pitched End-to-End Automation.
-- Emails marked "check" or "unverified" in the sheet are kept in notes, not used.
-- Skipped: True Gents Richmond (Multi-branch, drop); Samuels Barber (same phone as another row).
-- ==============================================================================

SET search_path TO "sales-pipe", public;

DROP TABLE IF EXISTS _import;
CREATE TEMP TABLE _import (business_name text, business_type text, category text, tier text, area text, postcode text, address text, phone text, whatsapp_number text, email text, instagram text, facebook text, existing_website text, google_rating numeric, google_reviews_count int, company_type text, contact_name text, notes text, service text);

INSERT INTO _import (business_name, business_type, category, tier, area, postcode, address, phone, whatsapp_number, email, instagram, facebook, existing_website, google_rating, google_reviews_count, company_type, contact_name, notes, service) VALUES
  ('Café NOVA Bistro', 'Cafe', 'Food & Drink', NULL, 'East Twickenham', 'TW1 2EB', '424 Richmond Rd, East Twickenham', '07453 302323', '07453 302323', NULL, 'cafenovabistro', NULL, NULL, 4.9, 653, 'Unknown', NULL, 'Open Mon to Fri 7am to 5pm, Sat and Sun 8am to 5pm. Website demo built. Sheet category: Cafe. Socials: Instagram', 'Website'),
  ('Mooca Café', 'Cafe', 'Food & Drink', NULL, 'Richmond', 'TW9 1EU', '7 Golden Ct, Richmond', '020 3345 1530', NULL, NULL, 'mooca_cafe_richmond', NULL, NULL, 4.7, 438, 'Unknown', NULL, 'Sheet category: Cafe. Socials: Instagram', 'Website'),
  ('Rich Café', 'Cafe', 'Food & Drink', NULL, 'East Twickenham', 'TW1 2EF', '435 Richmond Rd, East Twickenham', '020 4568 5234', NULL, NULL, NULL, NULL, NULL, 4.7, 304, 'Unknown', NULL, 'Sheet category: Cafe', 'Website'),
  ('QBrü Coffee', 'Cafe', 'Food & Drink', NULL, 'Richmond', 'TW9 2PQ', '96 Kew Rd, Richmond', '020 8940 0733', NULL, NULL, 'qbrucoffee', NULL, NULL, 4.5, 140, 'Unknown', NULL, 'Sheet category: Coffee shop. Socials: Instagram', 'Website'),
  ('Cafe Milano', 'Cafe', 'Food & Drink', NULL, 'Richmond', 'TW9 1AS', '8 Lichfield Ct, Sheen Rd, Richmond', '020 3659 4410', NULL, NULL, NULL, 'Cafe-Milano-Richmond', NULL, 4.8, 117, 'Unknown', NULL, 'Sheet category: Cafe. Socials: Facebook', 'Website'),
  ('Cafe Nano', 'Cafe', 'Food & Drink', NULL, 'Richmond', 'TW9 1UF', '76 Sheen Rd, Richmond', '07514 953005', '07514 953005', 'orders@partyplatter.co.uk', 'cafenano', 'Cafenanorichmond', 'Wix site', NULL, NULL, 'Unknown', NULL, 'Sheet category: Cafe. Socials: Instagram, Facebook. Linked to partyplatter.co.uk, weaker', 'Website'),
  ('Café Torelli', 'Cafe', 'Food & Drink', NULL, 'Kew', 'TW9 2PN', '131 Kew Rd, Richmond', NULL, NULL, NULL, 'cafetorellikew', NULL, NULL, 4.4, 63, 'Unknown', NULL, 'Sheet category: Coffee shop. Socials: Instagram, Facebook. Address mismatch, check', 'Website'),
  ('Magnolia Cafe', 'Cafe', 'Food & Drink', NULL, 'Twickenham', 'TW1 2TY', 'Cambridge Gardens Park, Twickenham', '07435 263633', '07435 263633', NULL, 'magnoliatreecafe', NULL, NULL, 4.8, 67, 'Unknown', NULL, 'Sheet category: Park cafe. Socials: Instagram. May have magnolia.cafe site', 'Website'),
  ('Eileen''s at Buccleuch Gardens', 'Cafe', 'Food & Drink', NULL, 'Richmond', 'TW10 6UX', 'Petersham Rd, Richmond', NULL, NULL, NULL, NULL, NULL, NULL, 4.7, 207, 'Unknown', NULL, 'Sheet category: Park cafe. Possible council concession', 'Website'),
  ('Mike''s Cafe', 'Cafe', 'Food & Drink', NULL, 'Notting Hill', 'W11 1NN', '12 Blenheim Cres', '020 7229 3757', NULL, NULL, 'mikescafeportobello', NULL, NULL, 4.6, 1065, 'Unknown', NULL, 'Sheet category: Cafe. Socials: Instagram, Facebook. Building was listed for sale', 'Website'),
  ('BNB Cafe and Bar', 'Cafe', 'Food & Drink', NULL, 'Notting Hill', 'W11 1EA', '219 Westbourne Park Rd', '020 7243 9223', NULL, NULL, NULL, NULL, NULL, 4.6, 835, 'Unknown', NULL, 'Sheet category: Cafe bar', 'Website'),
  ('Cafe de Fred', 'Cafe', 'Food & Drink', NULL, 'Kensington', 'W8 6EA', '10A Earls Ct Rd', '07960 722425', '07960 722425', NULL, 'cafe_defred', NULL, NULL, 4.8, 728, 'Unknown', NULL, 'Sheet category: Cafe. Socials: Instagram. Possible email orders@cafedefred.co.uk (unverified, not verified)', 'Website'),
  ('St Clair Cafe', 'Cafe', 'Food & Drink', NULL, 'Holland Park', 'W11 4QL', '98 Portland Rd', NULL, NULL, NULL, 'st.clair.cafe', NULL, NULL, 4.8, 121, 'Unknown', NULL, 'Sheet category: Cafe. Socials: Instagram', 'Website'),
  ('Kew Beauty Studio and Academy', 'Nails & Lashes', 'Beauty & Wellness', NULL, 'Kew', 'TW9', NULL, '07398 899889', '07398 899889', NULL, NULL, NULL, NULL, 5.0, 83, 'Unknown', NULL, 'Sheet category: Lashes & PMU. Socials: Instagram', 'Website'),
  ('The Nail Fairy and Beauty', 'Nails & Lashes', 'Beauty & Wellness', NULL, 'East Sheen', 'SW14', NULL, '020 3859 0971', NULL, NULL, NULL, NULL, NULL, 5.0, 60, 'Unknown', NULL, 'Sheet category: Nail salon. Socials: Instagram, Facebook', 'Website'),
  ('Karismatic Beauty and Nails', 'Nails & Lashes', 'Beauty & Wellness', NULL, 'East Sheen', 'SW14', NULL, '020 3612 1188', NULL, 'karismaticnailsandbeauty@gmail.com', NULL, NULL, NULL, 4.9, 155, 'Unknown', NULL, 'Sheet category: Beauty & nails. Socials: Instagram, Facebook', 'Website'),
  ('Skin & Beauty', 'Medical aesthetics', 'Beauty & Wellness', NULL, 'Mortlake', 'SW14', NULL, '07961 035351', '07961 035351', NULL, NULL, NULL, NULL, NULL, NULL, 'Unknown', NULL, 'Sheet category: Facialist & laser. Socials: Instagram. Owner: Sylwia', 'Website'),
  ('Irens Shine Beauty', 'Medical aesthetics', 'Beauty & Wellness', NULL, 'Kew', 'TW9', NULL, '07598 495777', '07598 495777', NULL, NULL, NULL, NULL, 4.5, NULL, 'Unknown', NULL, 'Sheet category: Aesthetics. Socials: Instagram', 'Website'),
  ('La bella Beauty', 'Beauty', 'Beauty & Wellness', NULL, 'Richmond', 'TW9', NULL, '07762 241209', '07762 241209', NULL, NULL, NULL, NULL, NULL, NULL, 'Unknown', NULL, 'Sheet category: Beauty salon. Socials: Instagram. Owner: Canan', 'Website'),
  ('Richmond Beauty', 'Beauty', 'Beauty & Wellness', NULL, 'Richmond', 'TW9', NULL, '07702 235273', '07702 235273', 'gemma@richmondbeauty.co.uk', NULL, NULL, NULL, NULL, NULL, 'Unknown', NULL, 'Sheet category: Beauty therapist. Socials: Treatwell. Owner: Gemma. May own domain', 'Website'),
  ('Harmony Nail Spa Wimbledon', 'Nails & Lashes', 'Beauty & Wellness', NULL, 'Wimbledon Village', 'SW19', NULL, '07449 686888', '07449 686888', NULL, NULL, NULL, NULL, NULL, NULL, 'Unknown', NULL, 'Sheet category: Nail salon. Socials: Instagram, Fresha. Owner: Szilvia', 'Website'),
  ('Chic&Cosy Nail Studio', 'Nails & Lashes', 'Beauty & Wellness', NULL, 'Merton', 'SW19', NULL, '07429 874992', '07429 874992', NULL, NULL, NULL, NULL, 5.0, 33, 'Unknown', NULL, 'Sheet category: Nail salon. Socials: Instagram', 'Website'),
  ('Pristine Nails Studio', 'Nails & Lashes', 'Beauty & Wellness', NULL, 'SW19', 'SW19', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5.0, 32, 'Unknown', NULL, 'Sheet category: Nail salon. Socials: Instagram', 'Website'),
  ('Nails by Mariya', 'Nails & Lashes', 'Beauty & Wellness', NULL, 'Wimbledon', 'SW19', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Unknown', NULL, 'Sheet category: Nail studio. Socials: Instagram. Owner: Mariya', 'Website'),
  ('J1 barber shop', 'Barber', 'Beauty & Wellness', NULL, 'Twickenham', 'TW1', NULL, '020 8001 9776', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram. Has marketing agency', 'Website'),
  ('A&N style Barbershop', 'Barber', 'Beauty & Wellness', NULL, 'Richmond', 'TW9', NULL, '020 8940 0534', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram (check). Also has Putney branch', 'Website'),
  ('Turkish Fade Twickenham', 'Barber', 'Beauty & Wellness', NULL, 'Twickenham', 'TW1', NULL, '07523 987557', '07523 987557', NULL, NULL, NULL, NULL, 4.9, 215, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram', 'Website'),
  ('Als Clip Joint', 'Barber', 'Beauty & Wellness', NULL, 'Kew', 'TW9', NULL, '07481 233320', '07481 233320', NULL, NULL, NULL, NULL, 4.8, 146, 'Unknown', NULL, 'Sheet category: Barber', 'Website'),
  ('public barbers', 'Barber', 'Beauty & Wellness', NULL, 'East Sheen', 'SW14', NULL, '020 8878 3571', NULL, NULL, NULL, NULL, NULL, 4.8, 107, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram (check)', 'Website'),
  ('The barber house', 'Barber', 'Beauty & Wellness', NULL, 'East Sheen', 'SW14', NULL, '07787 322231', '07787 322231', NULL, NULL, NULL, NULL, 4.9, 101, 'Unknown', NULL, 'Sheet category: Barber', 'Website'),
  ('Star Barbers', 'Barber', 'Beauty & Wellness', NULL, 'Richmond', 'TW9', NULL, '020 3158 9702', NULL, NULL, NULL, NULL, NULL, 5.0, 91, 'Unknown', NULL, 'Sheet category: Barber', 'Website'),
  ('The magic scissors', 'Barber', 'Beauty & Wellness', NULL, 'East Twickenham', 'TW1', NULL, '020 3158 4678', NULL, NULL, NULL, NULL, NULL, 5.0, 75, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram, Facebook', 'Website'),
  ('CUT4U Barber St Margaret''s', 'Barber', 'Beauty & Wellness', NULL, 'St Margarets', 'TW1', NULL, '07366 707071', '07366 707071', NULL, NULL, NULL, NULL, 5.0, 69, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram', 'Website'),
  ('Sheen in Style', 'Barber', 'Beauty & Wellness', NULL, 'East Sheen', 'SW14', NULL, '020 3859 8928', NULL, NULL, NULL, NULL, NULL, 5.0, 61, 'Unknown', NULL, 'Sheet category: Barber', 'Website'),
  ('SNAPCUT BARBERS', 'Barber', 'Beauty & Wellness', NULL, 'East Sheen', 'SW14', NULL, '020 7022 3985', NULL, NULL, NULL, NULL, NULL, 4.8, 47, 'Unknown', NULL, 'Sheet category: Barber', 'Website'),
  ('Wayne Connolly Painter', 'Other', 'Retail & Other', NULL, 'Teddington', 'TW11', NULL, '07506 133953', '07506 133953', NULL, NULL, NULL, NULL, 5.0, 41, 'Unknown', NULL, 'Sheet category: Painter & decorator. Socials: Instagram', 'Website'),
  ('Bespoke Decorating Services', 'Other', 'Retail & Other', NULL, 'Twickenham', 'TW1', NULL, '07500 210021', '07500 210021', NULL, NULL, NULL, NULL, 5.0, 21, 'Unknown', NULL, 'Sheet category: Painter & decorator. Socials: Facebook', 'Website'),
  ('The Chiswick Salon', 'Hair salon', 'Beauty & Wellness', NULL, 'Chiswick', 'W4', NULL, '020 8742 0202', NULL, 'thechiswicksalon@gmail.com', NULL, NULL, NULL, NULL, NULL, 'Unknown', NULL, 'Sheet category: Hairdresser. Socials: Instagram, Facebook. May have had a site', 'Website'),
  ('Maya lashes and beauty by Sunita', 'Nails & Lashes', 'Beauty & Wellness', NULL, 'Chiswick', 'W4', NULL, '07848 406372', '07848 406372', 'mayalashesandbeauty@gmail.com', NULL, NULL, NULL, 5.0, 96, 'Unknown', NULL, 'Sheet category: Lashes & beauty. Socials: Instagram, Facebook', 'Website'),
  ('Lestetica Beauty Studio', 'Beauty', 'Beauty & Wellness', NULL, 'Chiswick', 'W4', NULL, '07708 749242', '07708 749242', NULL, NULL, NULL, NULL, 5.0, 12, 'Unknown', NULL, 'Sheet category: Beauty salon', 'Website'),
  ('Carla Beauty Studio Chiswick', 'Beauty', 'Beauty & Wellness', NULL, 'Chiswick', 'W4', NULL, NULL, NULL, 'carlabeauty89@gmail.com', NULL, NULL, NULL, 5.0, 42, 'Unknown', NULL, 'Sheet category: Beautician. Socials: Instagram, Treatwell', 'Website'),
  ('Sam and Lee Barbers', 'Barber', 'Beauty & Wellness', NULL, 'Chiswick', 'W4', NULL, '07969 639893', '07969 639893', NULL, NULL, NULL, NULL, 4.7, 170, 'Unknown', NULL, 'Sheet category: Barber', 'Website'),
  ('CHRIS BARBERS', 'Barber', 'Beauty & Wellness', NULL, 'Chiswick', 'W4', NULL, '020 8117 6551', NULL, NULL, NULL, NULL, NULL, 4.8, 177, 'Unknown', NULL, 'Sheet category: Barber', 'Website'),
  ('Jimmy''s Gents Hairstylist', 'Barber', 'Beauty & Wellness', NULL, 'Chiswick', 'W4', NULL, '020 8995 2017', NULL, NULL, NULL, NULL, NULL, 4.6, 112, 'Unknown', NULL, 'Sheet category: Barber', 'Website'),
  ('JUDE BARBERS', 'Barber', 'Beauty & Wellness', NULL, 'Shepherd''s Bush', 'W12', NULL, '020 8746 0111', NULL, NULL, NULL, NULL, NULL, 4.9, 306, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram', 'Website'),
  ('Figaro Barber', 'Barber', 'Beauty & Wellness', NULL, 'Shepherd''s Bush', 'W12', NULL, '020 3302 3618', NULL, NULL, NULL, NULL, NULL, 4.9, 65, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram', 'Website'),
  ('Barber Shop & Co', 'Barber', 'Beauty & Wellness', NULL, 'Acton', 'W3', NULL, '020 3343 0537', NULL, NULL, NULL, NULL, NULL, 5.0, 35, 'Unknown', NULL, 'Sheet category: Barber', 'Website'),
  ('Blush Hair & Beauty', 'Hair salon', 'Beauty & Wellness', NULL, 'Putney Bridge', 'SW6', NULL, '020 4506 2964', NULL, NULL, NULL, NULL, NULL, 5.0, 34, 'Unknown', NULL, 'Sheet category: Hair & beauty', 'Website'),
  ('Anyma Color Studio & Head Spa', 'Hair salon', 'Beauty & Wellness', NULL, 'Fulham', 'SW6', NULL, '07354 960501', '07354 960501', NULL, NULL, NULL, NULL, 5.0, 38, 'Unknown', NULL, 'Sheet category: Hair colour & head spa. Socials: Instagram, Facebook', 'Website'),
  ('Studio 88 Hair, Nails & Beauty', 'Beauty', 'Beauty & Wellness', NULL, 'Wandsworth', 'SW18', NULL, '020 3325 1679', NULL, NULL, NULL, NULL, NULL, 4.8, 44, 'Unknown', NULL, 'Sheet category: Beauty salon', 'Website'),
  ('Keswick Barbers', 'Barber', 'Beauty & Wellness', NULL, 'Putney', 'SW15', NULL, '07898 411141', '07898 411141', NULL, NULL, NULL, NULL, 4.9, 700, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram', 'Website'),
  ('La Casa Barbers', 'Barber', 'Beauty & Wellness', NULL, 'Putney', 'SW15', NULL, '020 3062 5872', NULL, NULL, NULL, NULL, NULL, 5.0, 637, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram', 'Website'),
  ('Raza''s Barbers Putney', 'Barber', 'Beauty & Wellness', NULL, 'Putney', 'SW15', NULL, '020 8785 2806', NULL, NULL, NULL, NULL, NULL, 4.6, 284, 'Unknown', NULL, 'Sheet category: Barber', 'Website'),
  ('A&N Style Putney', 'Barber', 'Beauty & Wellness', NULL, 'Putney', 'SW15', NULL, '07836 445764', '07836 445764', NULL, NULL, NULL, NULL, NULL, NULL, 'Unknown', NULL, 'Sheet category: Barber. Socials: see #26. Same owner as #26 likely', 'Website'),
  ('Royal Moon Barber', 'Barber', 'Beauty & Wellness', NULL, 'Putney', 'SW15', NULL, '020 8785 3387', NULL, NULL, NULL, NULL, NULL, 5.0, 212, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram', 'Website'),
  ('Regal Barbers Putney Bridge', 'Barber', 'Beauty & Wellness', NULL, 'Putney Bridge', 'SW6', NULL, '020 3623 2011', NULL, NULL, NULL, NULL, NULL, 4.9, 153, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram (check)', 'Website'),
  ('Thebarber.al', 'Barber', 'Beauty & Wellness', NULL, 'Putney', 'SW15', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5.0, 146, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram', 'Website'),
  ('Zain Barbers', 'Barber', 'Beauty & Wellness', NULL, 'Putney', 'SW15', NULL, '07341 599555', '07341 599555', NULL, NULL, NULL, NULL, 5.0, 127, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram (check)', 'Website'),
  ('Head 2 Head Putney Ltd', 'Hair salon', 'Beauty & Wellness', NULL, 'Putney', 'SW15', NULL, '07951 217505', '07951 217505', NULL, NULL, NULL, NULL, NULL, NULL, 'Limited company', NULL, 'Sheet category: Hairdresser. Ltd company', 'Website'),
  ('Don Bigote', 'Barber', 'Beauty & Wellness', NULL, 'Fulham', 'SW6', NULL, '020 3441 4050', NULL, NULL, NULL, NULL, NULL, 4.6, 139, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram', 'Website'),
  ('Beauty Stories', 'Beauty', 'Beauty & Wellness', NULL, 'Fulham', 'SW6', NULL, '07775 727763', '07775 727763', NULL, NULL, NULL, NULL, 4.9, 111, 'Unknown', NULL, 'Sheet category: Beauty salon. Socials: Instagram', 'Website'),
  ('Poise Beauty Bar', 'Beauty', 'Beauty & Wellness', NULL, 'Fulham', 'SW6', NULL, '020 7736 8697', NULL, NULL, NULL, NULL, NULL, 4.6, 96, 'Unknown', NULL, 'Sheet category: Beauty salon. Socials: Instagram, Treatwell', 'Website'),
  ('Little Miss Beauty', 'Beauty', 'Beauty & Wellness', NULL, 'Fulham', 'SW6', NULL, '07985 766218', '07985 766218', 'little.missbeauty_@hotmail.com', NULL, NULL, NULL, 4.5, 51, 'Unknown', NULL, 'Sheet category: Beauty therapist. Socials: Treatwell', 'Website'),
  ('Five star beauty', 'Beauty', 'Beauty & Wellness', NULL, 'Hammersmith', 'W6', NULL, '07718 701360', '07718 701360', NULL, NULL, NULL, NULL, 4.8, 26, 'Unknown', NULL, 'Sheet category: Beauty therapist. Socials: Treatwell', 'Website'),
  ('Halo hair and beauty', 'Hair salon', 'Beauty & Wellness', NULL, 'Fulham', 'SW6', NULL, '020 3154 6444', NULL, NULL, NULL, NULL, NULL, 4.6, 30, 'Unknown', NULL, 'Sheet category: Hair & beauty. Socials: Instagram', 'Website'),
  ('Noble Barbers', 'Barber', 'Beauty & Wellness', NULL, 'Fulham', 'SW6', NULL, '07401 866167', '07401 866167', NULL, NULL, NULL, NULL, 4.9, 307, 'Unknown', NULL, 'Sheet category: Barber', 'Website'),
  ('Kaya Barbers', 'Barber', 'Beauty & Wellness', NULL, 'West Kensington', 'W14', NULL, '07931 671070', '07931 671070', NULL, NULL, NULL, NULL, 4.9, 439, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram', 'Website'),
  ('SW6 BARBERS', 'Barber', 'Beauty & Wellness', NULL, 'Fulham', 'SW6', NULL, '020 7731 7259', NULL, NULL, NULL, NULL, NULL, 4.8, 54, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram (check)', 'Website'),
  ('West Crew Cut', 'Barber', 'Beauty & Wellness', NULL, 'Fulham', 'SW6', NULL, '020 3509 7474', NULL, NULL, NULL, NULL, NULL, 4.9, 44, 'Unknown', NULL, 'Sheet category: Barber. Socials: Instagram', 'Website'),
  ('Geezer Barbers Fulham', 'Barber', 'Beauty & Wellness', NULL, 'Fulham', 'SW6', NULL, '07446 652993', '07446 652993', NULL, NULL, NULL, NULL, NULL, NULL, 'Unknown', NULL, 'Sheet category: Barber. Same owner as #72', 'Website'),
  ('Yappy Chappy', 'Other', 'Retail & Other', NULL, 'Battersea', 'SW11', NULL, '07757 055636', '07757 055636', NULL, NULL, NULL, NULL, NULL, NULL, 'Unknown', NULL, 'Sheet category: Dog groomer. Socials: Wix site. Free site only', 'Website'),
  ('Wild Thing Colombian Coffee', 'Cafe', 'Food & Drink', NULL, 'West Ealing', 'W13 0TL', '148 Broadway, West Ealing', '07710 580743', '07710 580743', NULL, 'wildthing.coffee', NULL, NULL, 4.9, 174, 'Unknown', 'Mauricio', 'Owner Mauricio. Website demo built.', 'Website'),
  ('Juliette''s Guest House', 'B&B / Guesthouse', 'Accommodation', NULL, 'Bayswater', 'W2', NULL, '020 7792 2401', NULL, NULL, NULL, NULL, 'julietts-guest.nhotel.online', 4.3, 92, 'Unknown', NULL, 'Sheet type: B&B. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Grand Hotel Bellevue', 'Hotel', 'Accommodation', NULL, 'Paddington', 'W2', NULL, '020 3089 2527', NULL, 'stay@grandhotelbellevuelondon.com', NULL, NULL, 'grandhotelbellevuelondon.com', 4.3, 146, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 4.3+', 'End-to-End Automation'),
  ('The Norfolk', 'Hotel', 'Accommodation', '4-5 star', 'Paddington', 'W2', NULL, '07444 550691', '07444 550691', NULL, NULL, NULL, 'thenorfolkpaddington.com', 4.3, 152, 'Unknown', NULL, 'Sheet type: 4-star. Independent, rating 4.3+', 'End-to-End Automation'),
  ('The Boathouse London', 'Hotel', 'Accommodation', '4-5 star', 'Paddington', 'W2', NULL, '07528 515363', '07528 515363', 'info@boathouselondon.co.uk', NULL, NULL, 'boathouselondon.co.uk', 4.8, 128, 'Unknown', NULL, 'Sheet type: 4-star. Independent, rating 4.3+', 'End-to-End Automation'),
  ('The Hayden Pub & Rooms', 'B&B / Guesthouse', 'Accommodation', NULL, 'Notting Hill', 'W2', NULL, '020 7229 2233', NULL, 'info@haydennottinghill.com', NULL, NULL, 'haydennottinghill.com', 4.6, 1368, 'Unknown', NULL, 'Sheet type: Pub with rooms. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Jubilee Hotel Victoria', 'Hotel', 'Accommodation', NULL, 'Pimlico', 'SW1V', NULL, '020 8243 8630', NULL, 'stay@jubileehotel.co.uk', NULL, NULL, 'jubileehotel.co.uk', 4.5, 309, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 4.3+', 'End-to-End Automation'),
  ('The Corner London City', 'Hotel', 'Accommodation', '3 star', 'Aldgate', 'E1', NULL, '020 3021 3300', NULL, NULL, NULL, NULL, 'thecornerlondoncity.co.uk', 4.4, 4087, 'Unknown', NULL, 'Sheet type: 3-star. Independent, rating 4.3+. Possible email daniel.dias@thecornerlondoncity.co.uk (staff, check role, not verified)', 'End-to-End Automation'),
  ('The Rookery', 'Hotel', 'Accommodation', '4-5 star', 'Clerkenwell', 'EC1M', NULL, '020 7336 0931', NULL, 'reservations@rookery.co.uk', NULL, NULL, 'rookeryhotel.com', 4.6, 350, 'Unknown', NULL, 'Sheet type: 4-star. Independent, rating 4.3+', 'End-to-End Automation'),
  ('The Mandrake', 'Hotel', 'Accommodation', '4-5 star', 'Fitzrovia', 'W1T', NULL, '020 3146 7770', NULL, 'enquiries@themandrake.com', NULL, NULL, 'themandrake.com', 4.4, 940, 'Unknown', NULL, 'Sheet type: 5-star. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Broadwick Soho', 'Hotel', 'Accommodation', '4-5 star', 'Soho', 'W1F', NULL, '020 7047 4000', NULL, 'reservations@broadwicksoho.com', NULL, NULL, 'broadwicksoho.com', 4.7, 278, 'Unknown', NULL, 'Sheet type: 5-star. Independent, rating 4.3+', 'End-to-End Automation'),
  ('The One Tun Pub & Rooms', 'B&B / Guesthouse', 'Accommodation', NULL, 'Farringdon', 'EC1N', NULL, '020 7405 1521', NULL, 'info@onetun.co.uk', NULL, NULL, 'onetun.co.uk', 4.3, 667, 'Unknown', NULL, 'Sheet type: Pub with rooms. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Great Northern Hotel', 'Hotel', 'Accommodation', NULL, 'King''s Cross', 'N1C', NULL, '020 3388 0800', NULL, 'info@gnhlondon.com', NULL, NULL, 'kayagnhlondon.com', 4.3, 1150, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Bingham Riverhouse', 'Hotel', 'Accommodation', '4-5 star', 'Richmond', 'TW10', NULL, '020 8940 0902', NULL, NULL, NULL, NULL, 'binghamriverhouse.com', 4.6, 1027, 'Unknown', NULL, 'Sheet type: 4-star. Independent, rating 4.3+. Possible email membership@binghamriverhouse.com (check, not verified)', 'End-to-End Automation'),
  ('The Petersham Hotel', 'Hotel', 'Accommodation', NULL, 'Richmond', 'TW10', NULL, '020 8940 7471', NULL, 'enq@petershamhotel.co.uk', NULL, NULL, 'petershamhotel.co.uk', 4.5, 1023, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 4.3+', 'End-to-End Automation'),
  ('The Selwyn Hotel', 'Hotel', 'Accommodation', NULL, 'Richmond', 'TW9', NULL, '020 7167 3165', NULL, 'hello@theselwyn.com', NULL, NULL, 'theselwyn.com', 4.6, 301, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Kew Gardens Hotel', 'Hotel', 'Accommodation', NULL, 'Kew', 'TW9', NULL, '020 8940 2220', NULL, 'enquiries@kewgardenshotel.com', NULL, NULL, 'kewgardenshotel.com', 4.3, 883, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 4.3+', 'End-to-End Automation'),
  ('The Victoria', 'B&B / Guesthouse', 'Accommodation', NULL, 'East Sheen', 'SW14', NULL, '020 4629 8212', NULL, 'hello@victoriasheen.co.uk', NULL, NULL, 'victoriasheen.co.uk', 4.3, 493, 'Unknown', NULL, 'Sheet type: Pub with rooms. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Warren House', 'Hotel', 'Accommodation', NULL, 'Kingston', 'KT2', NULL, '020 8547 1777', NULL, 'info@warrenhouse.com', NULL, NULL, 'warrenhouse.com', 4.4, 1017, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Le Sorelle', 'B&B / Guesthouse', 'Accommodation', NULL, 'Isle of Dogs', 'E14', NULL, '07703 661259', '07703 661259', 'reservations-lesorelle@outlook.com', NULL, NULL, 'lesorelleriverbarge.com', 4.8, 140, 'Unknown', NULL, 'Sheet type: Barge B&B. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Goswell House', 'Hotel', 'Accommodation', NULL, 'Windsor', 'SL4', NULL, '01753 444444', NULL, 'stay@goswellhouse.co.uk', NULL, NULL, 'goswellhouse.co.uk', 4.4, 94, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 4.3+', 'End-to-End Automation'),
  ('The Prince Albert', 'Hotel', 'Accommodation', '3 star', 'Windsor', 'SL4', NULL, '01753 395345', NULL, 'princealbertwindsor@yahoo.com', NULL, NULL, 'theprincealbertwindsor.co.uk', 4.4, 493, 'Unknown', NULL, 'Sheet type: 3-star. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Sir Christopher Wren Hotel', 'Hotel', 'Accommodation', NULL, 'Windsor', 'SL4', NULL, '01753 442400', NULL, NULL, NULL, NULL, 'sirchristopherwren.co.uk', 4.3, 2264, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Royal Adelaide Hotel', 'Hotel', 'Accommodation', NULL, 'Windsor', 'SL4', NULL, '01753 863916', NULL, 'info@royaladelaide.com', NULL, NULL, 'royaladelaide.com', 4.3, 481, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Christopher Hotel Eton', 'Hotel', 'Accommodation', NULL, 'Eton', 'SL4', NULL, '01753 852359', NULL, 'reception@thechristopher.co.uk', NULL, NULL, 'thechristopher.co.uk', 4.5, 387, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 4.3+', 'End-to-End Automation'),
  ('The George Inn Eton', 'B&B / Guesthouse', 'Accommodation', NULL, 'Eton', 'SL4', NULL, '01753 861797', NULL, 'thegeorge@webrew.co.uk', NULL, NULL, 'georgeinn-eton.co.uk', 4.4, 1450, 'Unknown', NULL, 'Sheet type: Inn. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Crown & Cushion Inn', 'B&B / Guesthouse', 'Accommodation', NULL, 'Eton', 'SL4', NULL, '01753 861531', NULL, 'info@thecrownandcushioneton.co.uk', NULL, NULL, 'thecrownandcushioneton.co.uk', 4.5, 487, 'Unknown', NULL, 'Sheet type: Inn. Independent, rating 4.3+', 'End-to-End Automation'),
  ('Oakley Court', 'Hotel', 'Accommodation', '4-5 star', 'Windsor', 'SL4', NULL, '01753 609988', NULL, 'guestrelations@oakleycourt.co.uk', NULL, NULL, 'oakleycourt.co.uk', 4.5, 1474, 'Unknown', NULL, 'Sheet type: 4-star. Independent, rating 4.3+', 'End-to-End Automation'),
  ('The Crown Playhatch', 'B&B / Guesthouse', 'Accommodation', NULL, 'Reading', 'RG4', NULL, '0118 947 2872', NULL, 'book@thecrown.co.uk', NULL, NULL, 'thecrown.co.uk', 4.4, 1193, 'Unknown', NULL, 'Sheet type: Inn. Independent, rating 4.3+', 'End-to-End Automation'),
  ('The Montague on the Gardens', 'Hotel', 'Accommodation', '4-5 star', 'Bloomsbury', 'WC1B', NULL, '020 7637 1001', NULL, NULL, NULL, NULL, 'montaguehotel.com', 4.7, 1367, 'Unknown', NULL, 'Sheet type: 4-star. Chain or group', 'End-to-End Automation'),
  ('Morton Hotel', 'Hotel', 'Accommodation', NULL, 'Bloomsbury', 'WC1H', NULL, '020 7692 5600', NULL, NULL, NULL, NULL, 'imperialhotels.co.uk', 4.5, 275, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('The Megaro', 'Hotel', 'Accommodation', '4-5 star', 'King''s Cross', 'WC1H', NULL, '020 7843 2222', NULL, NULL, NULL, NULL, 'themegarocollection.com', 4.3, 908, 'Unknown', NULL, 'Sheet type: 5-star. Chain or group', 'End-to-End Automation'),
  ('Treehouse Hotel London', 'Hotel', 'Accommodation', NULL, 'Marylebone', 'W1B', NULL, '020 7580 0111', NULL, NULL, NULL, NULL, 'treehousehotels.com', 4.5, 852, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Wilde Aparthotels Paddington', 'Hotel', 'Accommodation', '4-5 star', 'Paddington', 'W2', NULL, '020 3687 2480', NULL, NULL, NULL, NULL, 'wilde.com', 4.8, 3562, 'Unknown', NULL, 'Sheet type: 4-star. Chain or group', 'End-to-End Automation'),
  ('Roseate House London', 'Hotel', 'Accommodation', '4-5 star', 'Paddington', 'W2', NULL, '020 7479 6600', NULL, NULL, NULL, NULL, 'roseatehotels.com', 4.3, 641, 'Unknown', NULL, 'Sheet type: 5-star. Chain or group', 'End-to-End Automation'),
  ('The Soho Hotel', 'Hotel', 'Accommodation', NULL, 'Soho', 'W1D', NULL, '020 7559 3000', NULL, NULL, NULL, NULL, 'firmdalehotels.com', 4.6, 1636, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Kettner''s', 'Hotel', 'Accommodation', '3 star', 'Soho', 'W1D', NULL, '020 7734 5650', NULL, NULL, NULL, NULL, 'sohohouse.com', 4.5, 772, 'Unknown', NULL, 'Sheet type: 3-star. Chain or group', 'End-to-End Automation'),
  ('The Hoxton Holborn', 'Hotel', 'Accommodation', '4-5 star', 'Holborn', 'WC1V', NULL, '020 7661 3000', NULL, NULL, NULL, NULL, 'thehoxton.com', 4.5, 3890, 'Unknown', NULL, 'Sheet type: 4-star. Chain or group', 'End-to-End Automation'),
  ('The Standard London', 'Hotel', 'Accommodation', '4-5 star', 'King''s Cross', 'WC1H', NULL, '020 3981 8888', NULL, NULL, NULL, NULL, 'hyatt.com', 4.3, 1660, 'Unknown', NULL, 'Sheet type: 5-star. Chain or group', 'End-to-End Automation'),
  ('NoMad London', 'Hotel', 'Accommodation', '4-5 star', 'Covent Garden', 'WC2E', NULL, '020 3906 1600', NULL, NULL, NULL, NULL, 'hilton.com', 4.6, 1111, 'Unknown', NULL, 'Sheet type: 5-star. Chain or group', 'End-to-End Automation'),
  ('Orange Tree', 'B&B / Guesthouse', 'Accommodation', NULL, 'Richmond', 'TW9', NULL, '020 8940 0944', NULL, 'orangetree@youngs.co.uk', NULL, NULL, 'orangetreerichmond.co.uk', 4.3, 1427, 'Unknown', NULL, 'Sheet type: Pub with rooms. Chain or group', 'End-to-End Automation'),
  ('Coach & Horses Kew', 'B&B / Guesthouse', 'Accommodation', NULL, 'Kew', 'TW9', NULL, '020 8940 1208', NULL, 'coachandhorses@youngs.co.uk', NULL, NULL, 'coachhotelkew.co.uk', 4.4, 1275, 'Unknown', NULL, 'Sheet type: Pub with rooms. Chain or group', 'End-to-End Automation'),
  ('Alexander Pope', 'B&B / Guesthouse', 'Accommodation', NULL, 'Twickenham', 'TW1', NULL, '020 8892 3050', NULL, 'alexanderpope@youngs.co.uk', NULL, NULL, 'alexanderpope.co.uk', 4.3, 933, 'Unknown', NULL, 'Sheet type: Pub with rooms. Chain or group', 'End-to-End Automation'),
  ('Clayton Hotel Chiswick', 'Hotel', 'Accommodation', NULL, 'Chiswick', 'W4', NULL, '020 8996 5200', NULL, NULL, NULL, NULL, NULL, 4.3, 2887, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Innkeeper''s Collection Greenwich', 'B&B / Guesthouse', 'Accommodation', NULL, 'Greenwich', 'SE10', NULL, '020 8293 0037', NULL, NULL, NULL, NULL, 'innkeeperscollection.co.uk', 4.4, 433, 'Unknown', NULL, 'Sheet type: Inn. Chain or group', 'End-to-End Automation'),
  ('Cove Landmark Pinnacle', 'Hotel', 'Accommodation', '4-5 star', 'Canary Wharf', 'E14', NULL, '020 3972 4169', NULL, NULL, NULL, NULL, 'lockeliving.com', 4.4, 359, 'Unknown', NULL, 'Sheet type: 4-star. Chain or group', 'End-to-End Automation'),
  ('Macdonald Windsor Hotel', 'Hotel', 'Accommodation', NULL, 'Windsor', 'SL4', NULL, '0344 879 9101', NULL, NULL, NULL, NULL, 'macdonaldhotels.co.uk', 4.4, 1759, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Castle Hotel Windsor', 'Hotel', 'Accommodation', NULL, 'Windsor', 'SL4', NULL, '01753 851577', NULL, NULL, NULL, NULL, 'castlehotelwindsor.com', 4.4, 1475, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Monkey Island Estate', 'Hotel', 'Accommodation', '4-5 star', 'Bray', 'SL6', NULL, '01628 623400', NULL, NULL, NULL, NULL, 'monkeyislandestate.co.uk', 4.5, 534, 'Unknown', NULL, 'Sheet type: 5-star. Chain or group', 'End-to-End Automation'),
  ('Village Hotel Reading', 'Hotel', 'Accommodation', NULL, 'Reading', 'RG1', NULL, '0333 006 5222', NULL, NULL, NULL, NULL, 'village-hotels.co.uk', 4.6, 263, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('The Roseate Reading', 'Hotel', 'Accommodation', '4-5 star', 'Reading', 'RG1', NULL, '0118 952 7770', NULL, NULL, NULL, NULL, 'roseatehotels.com', 4.4, 708, 'Unknown', NULL, 'Sheet type: 5-star. Chain or group', 'End-to-End Automation'),
  ('Chrysos Hotel', 'Hotel', 'Accommodation', NULL, 'Paddington', 'W2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3.5, 382, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 3.5 to 4.3', 'End-to-End Automation'),
  ('The 55 by Le Mirage', 'Hotel', 'Accommodation', '4-5 star', 'Bayswater', 'W2', NULL, '020 4502 5800', NULL, 'reservations@the55lemirage.com', NULL, NULL, 'the55lemirage.com', 4.2, 280, 'Unknown', NULL, 'Sheet type: 4-star. Independent, rating 3.5 to 4.3', 'End-to-End Automation'),
  ('Phoenix Hotel', 'Hotel', 'Accommodation', NULL, 'Bayswater', 'W2', NULL, '020 7229 2494', NULL, 'reservations@phoenixhotel.co.uk', NULL, NULL, 'phoenixhotel.co.uk', 4.2, 1496, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 3.5 to 4.3', 'End-to-End Automation'),
  ('Otherwander Soho', 'Hotel', 'Accommodation', NULL, 'Soho', 'W1D', NULL, NULL, NULL, 'soho@otherwander.com', NULL, NULL, 'otherwander.com', 4.2, 160, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 3.5 to 4.3', 'End-to-End Automation'),
  ('The Wesley Euston', 'Hotel', 'Accommodation', '4-5 star', 'Euston', 'NW1', NULL, '020 7380 0001', NULL, 'reservations@thewesley.co.uk', NULL, NULL, 'thewesley.co.uk', 3.9, 1922, 'Unknown', NULL, 'Sheet type: 4-star. Independent, rating 3.5 to 4.3', 'End-to-End Automation'),
  ('Mimi''s Hotel Soho', 'Hotel', 'Accommodation', NULL, 'Soho', 'W1D', NULL, '020 8017 9100', NULL, 'info@mimishotelsoho.com', NULL, NULL, 'mimishotelsoho.com', 4.0, 952, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 3.5 to 4.3', 'End-to-End Automation'),
  ('NOX Richmond', 'Hotel', 'Accommodation', '3 star', 'Richmond', 'TW10', NULL, '020 4559 9766', NULL, 'richmond@noxhotels.co.uk', NULL, NULL, 'noxhotels.co.uk', 3.7, 140, 'Unknown', NULL, 'Sheet type: 3-star. Independent, rating 3.5 to 4.3. small group', 'End-to-End Automation'),
  ('Richmond Hill Hotel', 'Hotel', 'Accommodation', NULL, 'Richmond', 'TW10', NULL, '020 8940 2247', NULL, 'info@richmondhill.co.uk', NULL, NULL, 'richmondhill-hotel.co.uk', 4.2, 1266, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 3.5 to 4.3', 'End-to-End Automation'),
  ('The Bridge Inn', 'B&B / Guesthouse', 'Accommodation', NULL, 'Isleworth', 'TW7', NULL, '020 8568 0088', NULL, 'thebridgeinn@btconnect.com', NULL, NULL, NULL, 4.1, 343, 'Unknown', NULL, 'Sheet type: Inn. Independent, rating 3.5 to 4.3', 'End-to-End Automation'),
  ('Rose of York', 'B&B / Guesthouse', 'Accommodation', NULL, 'Richmond', 'TW10', NULL, '020 8948 5867', NULL, 'info@roseofyorkrichmond.co.uk', NULL, NULL, 'roseofyorkrichmond.co.uk', 4.0, 477, 'Unknown', NULL, 'Sheet type: Pub with rooms. Independent, rating 3.5 to 4.3', 'End-to-End Automation'),
  ('Park Grand Heathrow', 'Hotel', 'Accommodation', '4-5 star', 'Hounslow', 'TW5', NULL, '020 3118 9600', NULL, 'info@parkgrandheathrow.co.uk', NULL, NULL, 'parkgrandheathrow.co.uk', 3.9, 1799, 'Unknown', NULL, 'Sheet type: 4-star. Independent, rating 3.5 to 4.3. small group', 'End-to-End Automation'),
  ('Hotel 1843', 'Hotel', 'Accommodation', NULL, 'Reading', 'RG1', NULL, '0118 950 3925', NULL, 'info@1843reading.com', NULL, NULL, '1843reading.com', 3.9, 138, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 3.5 to 4.3. Hamlet Hotels', 'End-to-End Automation'),
  ('Parkside International Hotel', 'Hotel', 'Accommodation', NULL, 'Reading', 'RG30', NULL, '0118 959 0564', NULL, 'res@parksideinternationalhotel.com', NULL, NULL, 'parksideinternationalhotel.com', 3.6, 317, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 3.5 to 4.3', 'End-to-End Automation'),
  ('Abbey House Hotel', 'Hotel', 'Accommodation', NULL, 'Reading', 'RG30', NULL, '0118 961 5973', NULL, 'bookings@theabbeyhousehotel.co.uk', NULL, NULL, 'theabbeyhousehotel.co.uk', 3.5, 83, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 3.5 to 4.3', 'End-to-End Automation'),
  ('The Clarendon Hotel', 'Hotel', 'Accommodation', NULL, 'Blackheath', 'SE3', NULL, '020 8318 4321', NULL, 'foh@clarendonhotel.com', NULL, NULL, 'clarendonhotel.com', 4.2, 2214, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 3.5 to 4.3', 'End-to-End Automation'),
  ('The Angerstein Hotel', 'Hotel', 'Accommodation', NULL, 'Greenwich', 'SE10', NULL, '020 8293 5695', NULL, 'theangerstein@gmail.com', NULL, NULL, 'theangerstein.com', 4.0, 535, 'Unknown', NULL, 'Sheet type: Hotel. Independent, rating 3.5 to 4.3', 'End-to-End Automation'),
  ('Inhabit Queen''s Gardens', 'Hotel', 'Accommodation', NULL, 'Bayswater', 'W2', NULL, '020 7298 9800', NULL, 'dm.queensgardens@inhabithotels.com', NULL, NULL, 'inhabithotels.com', 3.9, 675, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Copthorne Tara Kensington', 'Hotel', 'Accommodation', NULL, 'Kensington', 'W8', NULL, '020 7937 7211', NULL, 'reservations.tara@millenniumhotels.co.uk', NULL, NULL, 'millenniumhotels.com', 3.9, 10200, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Ember Locke Kensington', 'Hotel', 'Accommodation', '4-5 star', 'Earl''s Court', 'SW5', NULL, '020 7052 7175', NULL, 'askember@lockeliving.com', NULL, NULL, 'lockeliving.com', 3.8, 357, 'Unknown', NULL, 'Sheet type: 4-star. Chain or group', 'End-to-End Automation'),
  ('Millennium Gloucester', 'Hotel', 'Accommodation', NULL, 'South Kensington', 'SW7', NULL, '020 7373 6030', NULL, 'reservations.gloucester@millenniumhotels.com', NULL, NULL, 'millenniumhotels.com', 3.9, 6646, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Hatton Garden Hotel', 'Hotel', 'Accommodation', NULL, 'Farringdon', 'EC1N', NULL, '020 3146 1385', NULL, 'reservations@crowngroupofhotels.com', NULL, NULL, 'crowngroupofhotels.com', 4.2, 368, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Hotel AMANO Covent Garden', 'Hotel', 'Accommodation', NULL, 'Covent Garden', 'WC2B', NULL, '020 3739 8900', NULL, 'coventgarden@amanogroup.com', NULL, NULL, 'amanogroup.com', 4.2, 674, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Royal National Hotel', 'Hotel', 'Accommodation', NULL, 'Bloomsbury', 'WC1H', NULL, '020 7637 2488', NULL, 'rnational@imperialhotels.co.uk', NULL, NULL, 'imperialhotels.co.uk', 3.6, 18062, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Harbour Hotel Richmond', 'Hotel', 'Accommodation', NULL, 'Richmond', 'TW10', NULL, '020 8940 0061', NULL, 'richmond@harbourhotels.co.uk', NULL, NULL, 'harbourhotels.co.uk', 3.9, 839, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Harte and Garter Hotel', 'Hotel', 'Accommodation', NULL, 'Windsor', 'SL4', NULL, '07908 657187', '07908 657187', 'harteandgarter@criterionhospitality.com', NULL, NULL, 'harteandgarter.com', 3.7, 664, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Copthorne Slough-Windsor', 'Hotel', 'Accommodation', NULL, 'Slough', 'SL1', NULL, '01753 516222', NULL, 'sales.slough@millenniumhotels.com', NULL, NULL, 'millenniumhotels.com', 3.8, 3329, 'Unknown', NULL, 'Sheet type: Hotel. Chain or group', 'End-to-End Automation'),
  ('Pentahotel Reading', 'Hotel', 'Accommodation', '4-5 star', 'Reading', 'RG1', NULL, '0118 230 8692', NULL, 'info.reading@pentahotels.com', NULL, NULL, 'pentahotels.com', 4.1, 2414, 'Unknown', NULL, 'Sheet type: 4-star. Chain or group', 'End-to-End Automation'),
  ('Malmaison Reading', 'Hotel', 'Accommodation', '4-5 star', 'Reading', 'RG1', NULL, '0118 334 1331', NULL, 'reading@malmaison.com', NULL, NULL, 'malmaison.com', 4.2, 803, 'Unknown', NULL, 'Sheet type: 4-star. Chain or group', 'End-to-End Automation'),
  ('Market House', 'B&B / Guesthouse', 'Accommodation', NULL, 'Reading', 'RG1', NULL, '0118 216 1750', NULL, 'markethouse@youngs.co.uk', NULL, NULL, 'markethousereading.com', 4.2, 635, 'Unknown', NULL, 'Sheet type: Pub with rooms. Chain or group', 'End-to-End Automation'),
  ('ARK Canary Wharf', 'Serviced apartments', 'Accommodation', NULL, 'Canary Wharf', 'E14', NULL, '020 3921 0562', NULL, 'canarywharf@arkcoliving.com', NULL, NULL, 'arkliving.com', 3.8, 1674, 'Unknown', NULL, 'Sheet type: Co-living. Chain or group', 'End-to-End Automation');

WITH new_rows AS (
  SELECT i.* FROM _import i
  WHERE NOT EXISTS (SELECT 1 FROM "sales-pipe".businesses b WHERE lower(b.business_name) = lower(i.business_name))
    AND (i.phone IS NULL OR NOT EXISTS (
          SELECT 1 FROM "sales-pipe".businesses b
          WHERE b.phone_normalised = "sales-pipe".normalise_phone(i.phone)))
    AND (i.email IS NULL OR NOT EXISTS (
          SELECT 1 FROM "sales-pipe".businesses b
          WHERE b.email_normalised = "sales-pipe".normalise_email(i.email)))
),
ins AS (
  INSERT INTO "sales-pipe".businesses (
    business_name, business_type, category, tier, area, postcode, address, phone, whatsapp_number,
    email, instagram, facebook, existing_website, google_rating, google_reviews_count,
    company_type, contact_name, notes
  )
  SELECT business_name, business_type, category, tier, area, postcode, address, phone, whatsapp_number,
         email, instagram, facebook, existing_website, google_rating, google_reviews_count,
         company_type, contact_name, notes
  FROM new_rows
  RETURNING id, business_name
)
INSERT INTO "sales-pipe".opportunities (business_id, services_pitched, stage)
SELECT ins.id, ARRAY[n.service], 'Needs review'
FROM ins JOIN new_rows n ON n.business_name = ins.business_name;

DROP TABLE IF EXISTS _import;

-- Check: how many leads per service and type
SELECT o.services_pitched[1] AS service, b.business_type, count(*) AS leads
FROM "sales-pipe".opportunities o JOIN "sales-pipe".businesses b ON b.id = o.business_id
WHERE o.stage = 'Needs review'
GROUP BY 1, 2 ORDER BY 1, 3 DESC;
