/**
 * DEMO MODE: imported leads from the Marketing Outreach database (Website and Hotels tabs).
 * Generated from the spreadsheet. All start as "Needs review" with no outreach yet.
 */
export const IMPORTED_LEADS: Record<string, any>[] = [
 {
  "business_name": "Kew Beauty Studio and Academy",
  "business_type": "Nails & Lashes",
  "category": "Beauty & Wellness",
  "area": "Kew",
  "postcode": "TW9",
  "phone": "07398 899889",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 83,
  "notes": "Sheet category: Lashes & PMU. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "The Nail Fairy and Beauty",
  "business_type": "Nails & Lashes",
  "category": "Beauty & Wellness",
  "area": "East Sheen",
  "postcode": "SW14",
  "phone": "020 3859 0971",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 60,
  "notes": "Sheet category: Nail salon. Socials: Instagram, Facebook",
  "service": "Website"
 },
 {
  "business_name": "Karismatic Beauty and Nails",
  "business_type": "Nails & Lashes",
  "category": "Beauty & Wellness",
  "area": "East Sheen",
  "postcode": "SW14",
  "phone": "020 3612 1188",
  "email": "karismaticnailsandbeauty@gmail.com",
  "google_rating": 4.9,
  "google_reviews_count": 155,
  "notes": "Sheet category: Beauty & nails. Socials: Instagram, Facebook",
  "service": "Website"
 },
 {
  "business_name": "Skin & Beauty",
  "business_type": "Medical aesthetics",
  "category": "Beauty & Wellness",
  "area": "Mortlake",
  "postcode": "SW14",
  "phone": "07961 035351",
  "email": null,
  "google_rating": null,
  "google_reviews_count": null,
  "notes": "Sheet category: Facialist & laser. Socials: Instagram. Owner: Sylwia",
  "service": "Website"
 },
 {
  "business_name": "Irens Shine Beauty",
  "business_type": "Medical aesthetics",
  "category": "Beauty & Wellness",
  "area": "Kew",
  "postcode": "TW9",
  "phone": "07598 495777",
  "email": null,
  "google_rating": 4.5,
  "google_reviews_count": null,
  "notes": "Sheet category: Aesthetics. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "La bella Beauty",
  "business_type": "Beauty",
  "category": "Beauty & Wellness",
  "area": "Richmond",
  "postcode": "TW9",
  "phone": "07762 241209",
  "email": null,
  "google_rating": null,
  "google_reviews_count": null,
  "notes": "Sheet category: Beauty salon. Socials: Instagram. Owner: Canan",
  "service": "Website"
 },
 {
  "business_name": "Richmond Beauty",
  "business_type": "Beauty",
  "category": "Beauty & Wellness",
  "area": "Richmond",
  "postcode": "TW9",
  "phone": "07702 235273",
  "email": "gemma@richmondbeauty.co.uk",
  "google_rating": null,
  "google_reviews_count": null,
  "notes": "Sheet category: Beauty therapist. Socials: Treatwell. Owner: Gemma. May own domain",
  "service": "Website"
 },
 {
  "business_name": "Harmony Nail Spa Wimbledon",
  "business_type": "Nails & Lashes",
  "category": "Beauty & Wellness",
  "area": "Wimbledon Village",
  "postcode": "SW19",
  "phone": "07449 686888",
  "email": null,
  "google_rating": null,
  "google_reviews_count": null,
  "notes": "Sheet category: Nail salon. Socials: Instagram, Fresha. Owner: Szilvia",
  "service": "Website"
 },
 {
  "business_name": "Chic&Cosy Nail Studio",
  "business_type": "Nails & Lashes",
  "category": "Beauty & Wellness",
  "area": "Merton",
  "postcode": "SW19",
  "phone": "07429 874992",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 33,
  "notes": "Sheet category: Nail salon. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Pristine Nails Studio",
  "business_type": "Nails & Lashes",
  "category": "Beauty & Wellness",
  "area": "SW19",
  "postcode": "SW19",
  "phone": null,
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 32,
  "notes": "Sheet category: Nail salon. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Nails by Mariya",
  "business_type": "Nails & Lashes",
  "category": "Beauty & Wellness",
  "area": "Wimbledon",
  "postcode": "SW19",
  "phone": null,
  "email": null,
  "google_rating": null,
  "google_reviews_count": null,
  "notes": "Sheet category: Nail studio. Socials: Instagram. Owner: Mariya",
  "service": "Website"
 },
 {
  "business_name": "J1 barber shop",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Twickenham",
  "postcode": "TW1",
  "phone": "020 8001 9776",
  "email": null,
  "google_rating": null,
  "google_reviews_count": null,
  "notes": "Sheet category: Barber. Socials: Instagram. Has marketing agency",
  "service": "Website"
 },
 {
  "business_name": "A&N style Barbershop",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Richmond",
  "postcode": "TW9",
  "phone": "020 8940 0534",
  "email": null,
  "google_rating": null,
  "google_reviews_count": null,
  "notes": "Sheet category: Barber. Socials: Instagram (check). Also has Putney branch",
  "service": "Website"
 },
 {
  "business_name": "Turkish Fade Twickenham",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Twickenham",
  "postcode": "TW1",
  "phone": "07523 987557",
  "email": null,
  "google_rating": 4.9,
  "google_reviews_count": 215,
  "notes": "Sheet category: Barber. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Als Clip Joint",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Kew",
  "postcode": "TW9",
  "phone": "07481 233320",
  "email": null,
  "google_rating": 4.8,
  "google_reviews_count": 146,
  "notes": "Sheet category: Barber",
  "service": "Website"
 },
 {
  "business_name": "public barbers",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "East Sheen",
  "postcode": "SW14",
  "phone": "020 8878 3571",
  "email": null,
  "google_rating": 4.8,
  "google_reviews_count": 107,
  "notes": "Sheet category: Barber. Socials: Instagram (check)",
  "service": "Website"
 },
 {
  "business_name": "The barber house",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "East Sheen",
  "postcode": "SW14",
  "phone": "07787 322231",
  "email": null,
  "google_rating": 4.9,
  "google_reviews_count": 101,
  "notes": "Sheet category: Barber",
  "service": "Website"
 },
 {
  "business_name": "Star Barbers",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Richmond",
  "postcode": "TW9",
  "phone": "020 3158 9702",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 91,
  "notes": "Sheet category: Barber",
  "service": "Website"
 },
 {
  "business_name": "The magic scissors",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "East Twickenham",
  "postcode": "TW1",
  "phone": "020 3158 4678",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 75,
  "notes": "Sheet category: Barber. Socials: Instagram, Facebook",
  "service": "Website"
 },
 {
  "business_name": "CUT4U Barber St Margaret's",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "St Margarets",
  "postcode": "TW1",
  "phone": "07366 707071",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 69,
  "notes": "Sheet category: Barber. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Sheen in Style",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "East Sheen",
  "postcode": "SW14",
  "phone": "020 3859 8928",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 61,
  "notes": "Sheet category: Barber",
  "service": "Website"
 },
 {
  "business_name": "SNAPCUT BARBERS",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "East Sheen",
  "postcode": "SW14",
  "phone": "020 7022 3985",
  "email": null,
  "google_rating": 4.8,
  "google_reviews_count": 47,
  "notes": "Sheet category: Barber",
  "service": "Website"
 },
 {
  "business_name": "Wayne Connolly Painter",
  "business_type": "Other",
  "category": "Retail & Other",
  "area": "Teddington",
  "postcode": "TW11",
  "phone": "07506 133953",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 41,
  "notes": "Sheet category: Painter & decorator. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Bespoke Decorating Services",
  "business_type": "Other",
  "category": "Retail & Other",
  "area": "Twickenham",
  "postcode": "TW1",
  "phone": "07500 210021",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 21,
  "notes": "Sheet category: Painter & decorator. Socials: Facebook",
  "service": "Website"
 },
 {
  "business_name": "The Chiswick Salon",
  "business_type": "Hair salon",
  "category": "Beauty & Wellness",
  "area": "Chiswick",
  "postcode": "W4",
  "phone": "020 8742 0202",
  "email": "thechiswicksalon@gmail.com",
  "google_rating": null,
  "google_reviews_count": null,
  "notes": "Sheet category: Hairdresser. Socials: Instagram, Facebook. May have had a site",
  "service": "Website"
 },
 {
  "business_name": "Maya lashes and beauty by Sunita",
  "business_type": "Nails & Lashes",
  "category": "Beauty & Wellness",
  "area": "Chiswick",
  "postcode": "W4",
  "phone": "07848 406372",
  "email": "mayalashesandbeauty@gmail.com",
  "google_rating": 5.0,
  "google_reviews_count": 96,
  "notes": "Sheet category: Lashes & beauty. Socials: Instagram, Facebook",
  "service": "Website"
 },
 {
  "business_name": "Lestetica Beauty Studio",
  "business_type": "Beauty",
  "category": "Beauty & Wellness",
  "area": "Chiswick",
  "postcode": "W4",
  "phone": "07708 749242",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 12,
  "notes": "Sheet category: Beauty salon",
  "service": "Website"
 },
 {
  "business_name": "Carla Beauty Studio Chiswick",
  "business_type": "Beauty",
  "category": "Beauty & Wellness",
  "area": "Chiswick",
  "postcode": "W4",
  "phone": null,
  "email": "carlabeauty89@gmail.com",
  "google_rating": 5.0,
  "google_reviews_count": 42,
  "notes": "Sheet category: Beautician. Socials: Instagram, Treatwell",
  "service": "Website"
 },
 {
  "business_name": "Sam and Lee Barbers",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Chiswick",
  "postcode": "W4",
  "phone": "07969 639893",
  "email": null,
  "google_rating": 4.7,
  "google_reviews_count": 170,
  "notes": "Sheet category: Barber",
  "service": "Website"
 },
 {
  "business_name": "CHRIS BARBERS",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Chiswick",
  "postcode": "W4",
  "phone": "020 8117 6551",
  "email": null,
  "google_rating": 4.8,
  "google_reviews_count": 177,
  "notes": "Sheet category: Barber",
  "service": "Website"
 },
 {
  "business_name": "Jimmy's Gents Hairstylist",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Chiswick",
  "postcode": "W4",
  "phone": "020 8995 2017",
  "email": null,
  "google_rating": 4.6,
  "google_reviews_count": 112,
  "notes": "Sheet category: Barber",
  "service": "Website"
 },
 {
  "business_name": "JUDE BARBERS",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Shepherd's Bush",
  "postcode": "W12",
  "phone": "020 8746 0111",
  "email": null,
  "google_rating": 4.9,
  "google_reviews_count": 306,
  "notes": "Sheet category: Barber. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Figaro Barber",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Shepherd's Bush",
  "postcode": "W12",
  "phone": "020 3302 3618",
  "email": null,
  "google_rating": 4.9,
  "google_reviews_count": 65,
  "notes": "Sheet category: Barber. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Barber Shop & Co",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Acton",
  "postcode": "W3",
  "phone": "020 3343 0537",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 35,
  "notes": "Sheet category: Barber",
  "service": "Website"
 },
 {
  "business_name": "Blush Hair & Beauty",
  "business_type": "Hair salon",
  "category": "Beauty & Wellness",
  "area": "Putney Bridge",
  "postcode": "SW6",
  "phone": "020 4506 2964",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 34,
  "notes": "Sheet category: Hair & beauty",
  "service": "Website"
 },
 {
  "business_name": "Anyma Color Studio & Head Spa",
  "business_type": "Hair salon",
  "category": "Beauty & Wellness",
  "area": "Fulham",
  "postcode": "SW6",
  "phone": "07354 960501",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 38,
  "notes": "Sheet category: Hair colour & head spa. Socials: Instagram, Facebook",
  "service": "Website"
 },
 {
  "business_name": "Studio 88 Hair, Nails & Beauty",
  "business_type": "Beauty",
  "category": "Beauty & Wellness",
  "area": "Wandsworth",
  "postcode": "SW18",
  "phone": "020 3325 1679",
  "email": null,
  "google_rating": 4.8,
  "google_reviews_count": 44,
  "notes": "Sheet category: Beauty salon",
  "service": "Website"
 },
 {
  "business_name": "Keswick Barbers",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Putney",
  "postcode": "SW15",
  "phone": "07898 411141",
  "email": null,
  "google_rating": 4.9,
  "google_reviews_count": 700,
  "notes": "Sheet category: Barber. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "La Casa Barbers",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Putney",
  "postcode": "SW15",
  "phone": "020 3062 5872",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 637,
  "notes": "Sheet category: Barber. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Raza's Barbers Putney",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Putney",
  "postcode": "SW15",
  "phone": "020 8785 2806",
  "email": null,
  "google_rating": 4.6,
  "google_reviews_count": 284,
  "notes": "Sheet category: Barber",
  "service": "Website"
 },
 {
  "business_name": "A&N Style Putney",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Putney",
  "postcode": "SW15",
  "phone": "07836 445764",
  "email": null,
  "google_rating": null,
  "google_reviews_count": null,
  "notes": "Sheet category: Barber. Socials: see #26. Same owner as #26 likely",
  "service": "Website"
 },
 {
  "business_name": "Royal Moon Barber",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Putney",
  "postcode": "SW15",
  "phone": "020 8785 3387",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 212,
  "notes": "Sheet category: Barber. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Regal Barbers Putney Bridge",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Putney Bridge",
  "postcode": "SW6",
  "phone": "020 3623 2011",
  "email": null,
  "google_rating": 4.9,
  "google_reviews_count": 153,
  "notes": "Sheet category: Barber. Socials: Instagram (check)",
  "service": "Website"
 },
 {
  "business_name": "Thebarber.al",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Putney",
  "postcode": "SW15",
  "phone": null,
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 146,
  "notes": "Sheet category: Barber. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Zain Barbers",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Putney",
  "postcode": "SW15",
  "phone": "07341 599555",
  "email": null,
  "google_rating": 5.0,
  "google_reviews_count": 127,
  "notes": "Sheet category: Barber. Socials: Instagram (check)",
  "service": "Website"
 },
 {
  "business_name": "Head 2 Head Putney Ltd",
  "business_type": "Hair salon",
  "category": "Beauty & Wellness",
  "area": "Putney",
  "postcode": "SW15",
  "phone": "07951 217505",
  "email": null,
  "google_rating": null,
  "google_reviews_count": null,
  "notes": "Sheet category: Hairdresser. Ltd company",
  "service": "Website"
 },
 {
  "business_name": "Don Bigote",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Fulham",
  "postcode": "SW6",
  "phone": "020 3441 4050",
  "email": null,
  "google_rating": 4.6,
  "google_reviews_count": 139,
  "notes": "Sheet category: Barber. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Beauty Stories",
  "business_type": "Beauty",
  "category": "Beauty & Wellness",
  "area": "Fulham",
  "postcode": "SW6",
  "phone": "07775 727763",
  "email": null,
  "google_rating": 4.9,
  "google_reviews_count": 111,
  "notes": "Sheet category: Beauty salon. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Poise Beauty Bar",
  "business_type": "Beauty",
  "category": "Beauty & Wellness",
  "area": "Fulham",
  "postcode": "SW6",
  "phone": "020 7736 8697",
  "email": null,
  "google_rating": 4.6,
  "google_reviews_count": 96,
  "notes": "Sheet category: Beauty salon. Socials: Instagram, Treatwell",
  "service": "Website"
 },
 {
  "business_name": "Little Miss Beauty",
  "business_type": "Beauty",
  "category": "Beauty & Wellness",
  "area": "Fulham",
  "postcode": "SW6",
  "phone": "07985 766218",
  "email": "little.missbeauty_@hotmail.com",
  "google_rating": 4.5,
  "google_reviews_count": 51,
  "notes": "Sheet category: Beauty therapist. Socials: Treatwell",
  "service": "Website"
 },
 {
  "business_name": "Five star beauty",
  "business_type": "Beauty",
  "category": "Beauty & Wellness",
  "area": "Hammersmith",
  "postcode": "W6",
  "phone": "07718 701360",
  "email": null,
  "google_rating": 4.8,
  "google_reviews_count": 26,
  "notes": "Sheet category: Beauty therapist. Socials: Treatwell",
  "service": "Website"
 },
 {
  "business_name": "Halo hair and beauty",
  "business_type": "Hair salon",
  "category": "Beauty & Wellness",
  "area": "Fulham",
  "postcode": "SW6",
  "phone": "020 3154 6444",
  "email": null,
  "google_rating": 4.6,
  "google_reviews_count": 30,
  "notes": "Sheet category: Hair & beauty. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Noble Barbers",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Fulham",
  "postcode": "SW6",
  "phone": "07401 866167",
  "email": null,
  "google_rating": 4.9,
  "google_reviews_count": 307,
  "notes": "Sheet category: Barber",
  "service": "Website"
 },
 {
  "business_name": "Kaya Barbers",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "West Kensington",
  "postcode": "W14",
  "phone": "07931 671070",
  "email": null,
  "google_rating": 4.9,
  "google_reviews_count": 439,
  "notes": "Sheet category: Barber. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "SW6 BARBERS",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Fulham",
  "postcode": "SW6",
  "phone": "020 7731 7259",
  "email": null,
  "google_rating": 4.8,
  "google_reviews_count": 54,
  "notes": "Sheet category: Barber. Socials: Instagram (check)",
  "service": "Website"
 },
 {
  "business_name": "West Crew Cut",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Fulham",
  "postcode": "SW6",
  "phone": "020 3509 7474",
  "email": null,
  "google_rating": 4.9,
  "google_reviews_count": 44,
  "notes": "Sheet category: Barber. Socials: Instagram",
  "service": "Website"
 },
 {
  "business_name": "Geezer Barbers Fulham",
  "business_type": "Barber",
  "category": "Beauty & Wellness",
  "area": "Fulham",
  "postcode": "SW6",
  "phone": "07446 652993",
  "email": null,
  "google_rating": null,
  "google_reviews_count": null,
  "notes": "Sheet category: Barber. Same owner as #72",
  "service": "Website"
 },
 {
  "business_name": "Yappy Chappy",
  "business_type": "Other",
  "category": "Retail & Other",
  "area": "Battersea",
  "postcode": "SW11",
  "phone": "07757 055636",
  "email": null,
  "google_rating": null,
  "google_reviews_count": null,
  "notes": "Sheet category: Dog groomer. Socials: Wix site. Free site only",
  "service": "Website"
 },
 {
  "business_name": "The Norfolk",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Paddington",
  "postcode": "W2",
  "phone": "07444 550691",
  "email": null,
  "existing_website": "thenorfolkpaddington.com",
  "google_rating": 4.3,
  "google_reviews_count": 152,
  "notes": "Sheet type: 4-star. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Hayden Pub & Rooms",
  "business_type": "B&B / Guesthouse",
  "tier": null,
  "category": "Accommodation",
  "area": "Notting Hill",
  "postcode": "W2",
  "phone": "020 7229 2233",
  "email": "info@haydennottinghill.com",
  "existing_website": "haydennottinghill.com",
  "google_rating": 4.6,
  "google_reviews_count": 1368,
  "notes": "Sheet type: Pub with rooms. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Corner London City",
  "business_type": "Hotel",
  "tier": "3 star",
  "category": "Accommodation",
  "area": "Aldgate",
  "postcode": "E1",
  "phone": "020 3021 3300",
  "email": "daniel.dias@thecornerlondoncity.co.uk",
  "existing_website": "thecornerlondoncity.co.uk",
  "google_rating": 4.4,
  "google_reviews_count": 4087,
  "notes": "Sheet type: 3-star. Independent (rating 4.3+). Email note: (staff, check role)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Rookery",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Clerkenwell",
  "postcode": "EC1M",
  "phone": "020 7336 0931",
  "email": "reservations@rookery.co.uk",
  "existing_website": "rookeryhotel.com",
  "google_rating": 4.6,
  "google_reviews_count": 350,
  "notes": "Sheet type: 4-star. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Mandrake",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Fitzrovia",
  "postcode": "W1T",
  "phone": "020 3146 7770",
  "email": "enquiries@themandrake.com",
  "existing_website": "themandrake.com",
  "google_rating": 4.4,
  "google_reviews_count": 940,
  "notes": "Sheet type: 5-star. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Broadwick Soho",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Soho",
  "postcode": "W1F",
  "phone": "020 7047 4000",
  "email": "reservations@broadwicksoho.com",
  "existing_website": "broadwicksoho.com",
  "google_rating": 4.7,
  "google_reviews_count": 278,
  "notes": "Sheet type: 5-star. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The One Tun Pub & Rooms",
  "business_type": "B&B / Guesthouse",
  "tier": null,
  "category": "Accommodation",
  "area": "Farringdon",
  "postcode": "EC1N",
  "phone": "020 7405 1521",
  "email": "info@onetun.co.uk",
  "existing_website": "onetun.co.uk",
  "google_rating": 4.3,
  "google_reviews_count": 667,
  "notes": "Sheet type: Pub with rooms. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Great Northern Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "King's Cross",
  "postcode": "N1C",
  "phone": "020 3388 0800",
  "email": "info@gnhlondon.com",
  "existing_website": "kayagnhlondon.com",
  "google_rating": 4.3,
  "google_reviews_count": 1150,
  "notes": "Sheet type: Hotel. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Bingham Riverhouse",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Richmond",
  "postcode": "TW10",
  "phone": "020 8940 0902",
  "email": "membership@binghamriverhouse.com",
  "existing_website": "binghamriverhouse.com",
  "google_rating": 4.6,
  "google_reviews_count": 1027,
  "notes": "Sheet type: 4-star. Independent (rating 4.3+). Email note: (check)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Petersham Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Richmond",
  "postcode": "TW10",
  "phone": "020 8940 7471",
  "email": "enq@petershamhotel.co.uk",
  "existing_website": "petershamhotel.co.uk",
  "google_rating": 4.5,
  "google_reviews_count": 1023,
  "notes": "Sheet type: Hotel. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Victoria",
  "business_type": "B&B / Guesthouse",
  "tier": null,
  "category": "Accommodation",
  "area": "East Sheen",
  "postcode": "SW14",
  "phone": "020 4629 8212",
  "email": "hello@victoriasheen.co.uk",
  "existing_website": "victoriasheen.co.uk",
  "google_rating": 4.3,
  "google_reviews_count": 493,
  "notes": "Sheet type: Pub with rooms. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Warren House",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Kingston",
  "postcode": "KT2",
  "phone": "020 8547 1777",
  "email": "info@warrenhouse.com",
  "existing_website": "warrenhouse.com",
  "google_rating": 4.4,
  "google_reviews_count": 1017,
  "notes": "Sheet type: Hotel. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Goswell House",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Windsor",
  "postcode": "SL4",
  "phone": "01753 444444",
  "email": "stay@goswellhouse.co.uk",
  "existing_website": "goswellhouse.co.uk",
  "google_rating": 4.4,
  "google_reviews_count": 94,
  "notes": "Sheet type: Hotel. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Prince Albert",
  "business_type": "Hotel",
  "tier": "3 star",
  "category": "Accommodation",
  "area": "Windsor",
  "postcode": "SL4",
  "phone": "01753 395345",
  "email": "princealbertwindsor@yahoo.com",
  "existing_website": "theprincealbertwindsor.co.uk",
  "google_rating": 4.4,
  "google_reviews_count": 493,
  "notes": "Sheet type: 3-star. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Sir Christopher Wren Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Windsor",
  "postcode": "SL4",
  "phone": "01753 442400",
  "email": null,
  "existing_website": "sirchristopherwren.co.uk",
  "google_rating": 4.3,
  "google_reviews_count": 2264,
  "notes": "Sheet type: Hotel. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Royal Adelaide Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Windsor",
  "postcode": "SL4",
  "phone": "01753 863916",
  "email": "info@royaladelaide.com",
  "existing_website": "royaladelaide.com",
  "google_rating": 4.3,
  "google_reviews_count": 481,
  "notes": "Sheet type: Hotel. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Christopher Hotel Eton",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Eton",
  "postcode": "SL4",
  "phone": "01753 852359",
  "email": "reception@thechristopher.co.uk",
  "existing_website": "thechristopher.co.uk",
  "google_rating": 4.5,
  "google_reviews_count": 387,
  "notes": "Sheet type: Hotel. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The George Inn Eton",
  "business_type": "B&B / Guesthouse",
  "tier": null,
  "category": "Accommodation",
  "area": "Eton",
  "postcode": "SL4",
  "phone": "01753 861797",
  "email": "thegeorge@webrew.co.uk",
  "existing_website": "georgeinn-eton.co.uk",
  "google_rating": 4.4,
  "google_reviews_count": 1450,
  "notes": "Sheet type: Inn. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Crown & Cushion Inn",
  "business_type": "B&B / Guesthouse",
  "tier": null,
  "category": "Accommodation",
  "area": "Eton",
  "postcode": "SL4",
  "phone": "01753 861531",
  "email": "info@thecrownandcushioneton.co.uk",
  "existing_website": "thecrownandcushioneton.co.uk",
  "google_rating": 4.5,
  "google_reviews_count": 487,
  "notes": "Sheet type: Inn. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Oakley Court",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Windsor",
  "postcode": "SL4",
  "phone": "01753 609988",
  "email": "guestrelations@oakleycourt.co.uk",
  "existing_website": "oakleycourt.co.uk",
  "google_rating": 4.5,
  "google_reviews_count": 1474,
  "notes": "Sheet type: 4-star. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Crown Playhatch",
  "business_type": "B&B / Guesthouse",
  "tier": null,
  "category": "Accommodation",
  "area": "Reading",
  "postcode": "RG4",
  "phone": "0118 947 2872",
  "email": "book@thecrown.co.uk",
  "existing_website": "thecrown.co.uk",
  "google_rating": 4.4,
  "google_reviews_count": 1193,
  "notes": "Sheet type: Inn. Independent (rating 4.3+)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Montague on the Gardens",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Bloomsbury",
  "postcode": "WC1B",
  "phone": "020 7637 1001",
  "email": null,
  "existing_website": "montaguehotel.com",
  "google_rating": 4.7,
  "google_reviews_count": 1367,
  "notes": "Sheet type: 4-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Morton Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Bloomsbury",
  "postcode": "WC1H",
  "phone": "020 7692 5600",
  "email": null,
  "existing_website": "imperialhotels.co.uk",
  "google_rating": 4.5,
  "google_reviews_count": 275,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Megaro",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "King's Cross",
  "postcode": "WC1H",
  "phone": "020 7843 2222",
  "email": null,
  "existing_website": "themegarocollection.com",
  "google_rating": 4.3,
  "google_reviews_count": 908,
  "notes": "Sheet type: 5-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Treehouse Hotel London",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Marylebone",
  "postcode": "W1B",
  "phone": "020 7580 0111",
  "email": null,
  "existing_website": "treehousehotels.com",
  "google_rating": 4.5,
  "google_reviews_count": 852,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Wilde Aparthotels Paddington",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Paddington",
  "postcode": "W2",
  "phone": "020 3687 2480",
  "email": null,
  "existing_website": "wilde.com",
  "google_rating": 4.8,
  "google_reviews_count": 3562,
  "notes": "Sheet type: 4-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Roseate House London",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Paddington",
  "postcode": "W2",
  "phone": "020 7479 6600",
  "email": null,
  "existing_website": "roseatehotels.com",
  "google_rating": 4.3,
  "google_reviews_count": 641,
  "notes": "Sheet type: 5-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Soho Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Soho",
  "postcode": "W1D",
  "phone": "020 7559 3000",
  "email": null,
  "existing_website": "firmdalehotels.com",
  "google_rating": 4.6,
  "google_reviews_count": 1636,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Kettner's",
  "business_type": "Hotel",
  "tier": "3 star",
  "category": "Accommodation",
  "area": "Soho",
  "postcode": "W1D",
  "phone": "020 7734 5650",
  "email": null,
  "existing_website": "sohohouse.com",
  "google_rating": 4.5,
  "google_reviews_count": 772,
  "notes": "Sheet type: 3-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Hoxton Holborn",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Holborn",
  "postcode": "WC1V",
  "phone": "020 7661 3000",
  "email": null,
  "existing_website": "thehoxton.com",
  "google_rating": 4.5,
  "google_reviews_count": 3890,
  "notes": "Sheet type: 4-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Standard London",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "King's Cross",
  "postcode": "WC1H",
  "phone": "020 3981 8888",
  "email": null,
  "existing_website": "hyatt.com",
  "google_rating": 4.3,
  "google_reviews_count": 1660,
  "notes": "Sheet type: 5-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "NoMad London",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Covent Garden",
  "postcode": "WC2E",
  "phone": "020 3906 1600",
  "email": null,
  "existing_website": "hilton.com",
  "google_rating": 4.6,
  "google_reviews_count": 1111,
  "notes": "Sheet type: 5-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Orange Tree",
  "business_type": "B&B / Guesthouse",
  "tier": null,
  "category": "Accommodation",
  "area": "Richmond",
  "postcode": "TW9",
  "phone": "020 8940 0944",
  "email": "orangetree@youngs.co.uk",
  "existing_website": "orangetreerichmond.co.uk",
  "google_rating": 4.3,
  "google_reviews_count": 1427,
  "notes": "Sheet type: Pub with rooms. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Coach & Horses Kew",
  "business_type": "B&B / Guesthouse",
  "tier": null,
  "category": "Accommodation",
  "area": "Kew",
  "postcode": "TW9",
  "phone": "020 8940 1208",
  "email": "coachandhorses@youngs.co.uk",
  "existing_website": "coachhotelkew.co.uk",
  "google_rating": 4.4,
  "google_reviews_count": 1275,
  "notes": "Sheet type: Pub with rooms. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Alexander Pope",
  "business_type": "B&B / Guesthouse",
  "tier": null,
  "category": "Accommodation",
  "area": "Twickenham",
  "postcode": "TW1",
  "phone": "020 8892 3050",
  "email": "alexanderpope@youngs.co.uk",
  "existing_website": "alexanderpope.co.uk",
  "google_rating": 4.3,
  "google_reviews_count": 933,
  "notes": "Sheet type: Pub with rooms. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Clayton Hotel Chiswick",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Chiswick",
  "postcode": "W4",
  "phone": "020 8996 5200",
  "email": null,
  "existing_website": null,
  "google_rating": 4.3,
  "google_reviews_count": 2887,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Innkeeper's Collection Greenwich",
  "business_type": "B&B / Guesthouse",
  "tier": null,
  "category": "Accommodation",
  "area": "Greenwich",
  "postcode": "SE10",
  "phone": "020 8293 0037",
  "email": null,
  "existing_website": "innkeeperscollection.co.uk",
  "google_rating": 4.4,
  "google_reviews_count": 433,
  "notes": "Sheet type: Inn. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Cove Landmark Pinnacle",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Canary Wharf",
  "postcode": "E14",
  "phone": "020 3972 4169",
  "email": null,
  "existing_website": "lockeliving.com",
  "google_rating": 4.4,
  "google_reviews_count": 359,
  "notes": "Sheet type: 4-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Macdonald Windsor Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Windsor",
  "postcode": "SL4",
  "phone": "0344 879 9101",
  "email": null,
  "existing_website": "macdonaldhotels.co.uk",
  "google_rating": 4.4,
  "google_reviews_count": 1759,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Castle Hotel Windsor",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Windsor",
  "postcode": "SL4",
  "phone": "01753 851577",
  "email": null,
  "existing_website": "castlehotelwindsor.com",
  "google_rating": 4.4,
  "google_reviews_count": 1475,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Monkey Island Estate",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Bray",
  "postcode": "SL6",
  "phone": "01628 623400",
  "email": null,
  "existing_website": "monkeyislandestate.co.uk",
  "google_rating": 4.5,
  "google_reviews_count": 534,
  "notes": "Sheet type: 5-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Village Hotel Reading",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Reading",
  "postcode": "RG1",
  "phone": "0333 006 5222",
  "email": null,
  "existing_website": "village-hotels.co.uk",
  "google_rating": 4.6,
  "google_reviews_count": 263,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Roseate Reading",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Reading",
  "postcode": "RG1",
  "phone": "0118 952 7770",
  "email": null,
  "existing_website": "roseatehotels.com",
  "google_rating": 4.4,
  "google_reviews_count": 708,
  "notes": "Sheet type: 5-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Chrysos Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Paddington",
  "postcode": "W2",
  "phone": null,
  "email": null,
  "existing_website": null,
  "google_rating": 3.5,
  "google_reviews_count": 382,
  "notes": "Sheet type: Hotel. Independent",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The 55 by Le Mirage",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Bayswater",
  "postcode": "W2",
  "phone": "020 4502 5800",
  "email": "reservations@the55lemirage.com",
  "existing_website": "the55lemirage.com",
  "google_rating": 4.2,
  "google_reviews_count": 280,
  "notes": "Sheet type: 4-star. Independent",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Phoenix Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Bayswater",
  "postcode": "W2",
  "phone": "020 7229 2494",
  "email": "reservations@phoenixhotel.co.uk",
  "existing_website": "phoenixhotel.co.uk",
  "google_rating": 4.2,
  "google_reviews_count": 1496,
  "notes": "Sheet type: Hotel. Independent",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Otherwander Soho",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Soho",
  "postcode": "W1D",
  "phone": null,
  "email": "soho@otherwander.com",
  "existing_website": "otherwander.com",
  "google_rating": 4.2,
  "google_reviews_count": 160,
  "notes": "Sheet type: Hotel. Independent",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Wesley Euston",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Euston",
  "postcode": "NW1",
  "phone": "020 7380 0001",
  "email": "reservations@thewesley.co.uk",
  "existing_website": "thewesley.co.uk",
  "google_rating": 3.9,
  "google_reviews_count": 1922,
  "notes": "Sheet type: 4-star. Independent",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Mimi's Hotel Soho",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Soho",
  "postcode": "W1D",
  "phone": "020 8017 9100",
  "email": "info@mimishotelsoho.com",
  "existing_website": "mimishotelsoho.com",
  "google_rating": 4.0,
  "google_reviews_count": 952,
  "notes": "Sheet type: Hotel. Independent",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "NOX Richmond",
  "business_type": "Hotel",
  "tier": "3 star",
  "category": "Accommodation",
  "area": "Richmond",
  "postcode": "TW10",
  "phone": "020 4559 9766",
  "email": "richmond@noxhotels.co.uk",
  "existing_website": "noxhotels.co.uk",
  "google_rating": 3.7,
  "google_reviews_count": 140,
  "notes": "Sheet type: 3-star. Independent. Email note: (small group)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Bridge Inn",
  "business_type": "B&B / Guesthouse",
  "tier": null,
  "category": "Accommodation",
  "area": "Isleworth",
  "postcode": "TW7",
  "phone": "020 8568 0088",
  "email": "thebridgeinn@btconnect.com",
  "existing_website": null,
  "google_rating": 4.1,
  "google_reviews_count": 343,
  "notes": "Sheet type: Inn. Independent",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Rose of York",
  "business_type": "B&B / Guesthouse",
  "tier": null,
  "category": "Accommodation",
  "area": "Richmond",
  "postcode": "TW10",
  "phone": "020 8948 5867",
  "email": "info@roseofyorkrichmond.co.uk",
  "existing_website": "roseofyorkrichmond.co.uk",
  "google_rating": 4.0,
  "google_reviews_count": 477,
  "notes": "Sheet type: Pub with rooms. Independent",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Park Grand Heathrow",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Hounslow",
  "postcode": "TW5",
  "phone": "020 3118 9600",
  "email": "info@parkgrandheathrow.co.uk",
  "existing_website": "parkgrandheathrow.co.uk",
  "google_rating": 3.9,
  "google_reviews_count": 1799,
  "notes": "Sheet type: 4-star. Independent. Email note: (small group)",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Parkside International Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Reading",
  "postcode": "RG30",
  "phone": "0118 959 0564",
  "email": "res@parksideinternationalhotel.com",
  "existing_website": "parksideinternationalhotel.com",
  "google_rating": 3.6,
  "google_reviews_count": 317,
  "notes": "Sheet type: Hotel. Independent",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Clarendon Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Blackheath",
  "postcode": "SE3",
  "phone": "020 8318 4321",
  "email": "foh@clarendonhotel.com",
  "existing_website": "clarendonhotel.com",
  "google_rating": 4.2,
  "google_reviews_count": 2214,
  "notes": "Sheet type: Hotel. Independent",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "The Angerstein Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Greenwich",
  "postcode": "SE10",
  "phone": "020 8293 5695",
  "email": "theangerstein@gmail.com",
  "existing_website": "theangerstein.com",
  "google_rating": 4.0,
  "google_reviews_count": 535,
  "notes": "Sheet type: Hotel. Independent",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Inhabit Queen's Gardens",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Bayswater",
  "postcode": "W2",
  "phone": "020 7298 9800",
  "email": "dm.queensgardens@inhabithotels.com",
  "existing_website": "inhabithotels.com",
  "google_rating": 3.9,
  "google_reviews_count": 675,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Copthorne Tara Kensington",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Kensington",
  "postcode": "W8",
  "phone": "020 7937 7211",
  "email": "reservations.tara@millenniumhotels.co.uk",
  "existing_website": "millenniumhotels.com",
  "google_rating": 3.9,
  "google_reviews_count": 10200,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Ember Locke Kensington",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Earl's Court",
  "postcode": "SW5",
  "phone": "020 7052 7175",
  "email": "askember@lockeliving.com",
  "existing_website": "lockeliving.com",
  "google_rating": 3.8,
  "google_reviews_count": 357,
  "notes": "Sheet type: 4-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Millennium Gloucester",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "South Kensington",
  "postcode": "SW7",
  "phone": "020 7373 6030",
  "email": "reservations.gloucester@millenniumhotels.com",
  "existing_website": "millenniumhotels.com",
  "google_rating": 3.9,
  "google_reviews_count": 6646,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Hatton Garden Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Farringdon",
  "postcode": "EC1N",
  "phone": "020 3146 1385",
  "email": "reservations@crowngroupofhotels.com",
  "existing_website": "crowngroupofhotels.com",
  "google_rating": 4.2,
  "google_reviews_count": 368,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Hotel AMANO Covent Garden",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Covent Garden",
  "postcode": "WC2B",
  "phone": "020 3739 8900",
  "email": "coventgarden@amanogroup.com",
  "existing_website": "amanogroup.com",
  "google_rating": 4.2,
  "google_reviews_count": 674,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Royal National Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Bloomsbury",
  "postcode": "WC1H",
  "phone": "020 7637 2488",
  "email": "rnational@imperialhotels.co.uk",
  "existing_website": "imperialhotels.co.uk",
  "google_rating": 3.6,
  "google_reviews_count": 18062,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Harbour Hotel Richmond",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Richmond",
  "postcode": "TW10",
  "phone": "020 8940 0061",
  "email": "richmond@harbourhotels.co.uk",
  "existing_website": "harbourhotels.co.uk",
  "google_rating": 3.9,
  "google_reviews_count": 839,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Harte and Garter Hotel",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Windsor",
  "postcode": "SL4",
  "phone": "07908 657187",
  "email": "harteandgarter@criterionhospitality.com",
  "existing_website": "harteandgarter.com",
  "google_rating": 3.7,
  "google_reviews_count": 664,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Copthorne Slough-Windsor",
  "business_type": "Hotel",
  "tier": null,
  "category": "Accommodation",
  "area": "Slough",
  "postcode": "SL1",
  "phone": "01753 516222",
  "email": "sales.slough@millenniumhotels.com",
  "existing_website": "millenniumhotels.com",
  "google_rating": 3.8,
  "google_reviews_count": 3329,
  "notes": "Sheet type: Hotel. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Pentahotel Reading",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Reading",
  "postcode": "RG1",
  "phone": "0118 230 8692",
  "email": "info.reading@pentahotels.com",
  "existing_website": "pentahotels.com",
  "google_rating": 4.1,
  "google_reviews_count": 2414,
  "notes": "Sheet type: 4-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Malmaison Reading",
  "business_type": "Hotel",
  "tier": "4-5 star",
  "category": "Accommodation",
  "area": "Reading",
  "postcode": "RG1",
  "phone": "0118 334 1331",
  "email": "reading@malmaison.com",
  "existing_website": "malmaison.com",
  "google_rating": 4.2,
  "google_reviews_count": 803,
  "notes": "Sheet type: 4-star. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "Market House",
  "business_type": "B&B / Guesthouse",
  "tier": null,
  "category": "Accommodation",
  "area": "Reading",
  "postcode": "RG1",
  "phone": "0118 216 1750",
  "email": "markethouse@youngs.co.uk",
  "existing_website": "markethousereading.com",
  "google_rating": 4.2,
  "google_reviews_count": 635,
  "notes": "Sheet type: Pub with rooms. Chain or group",
  "service": "End-to-End Automation"
 },
 {
  "business_name": "ARK Canary Wharf",
  "business_type": "Serviced apartments",
  "tier": null,
  "category": "Accommodation",
  "area": "Canary Wharf",
  "postcode": "E14",
  "phone": "020 3921 0562",
  "email": "canarywharf@arkcoliving.com",
  "existing_website": "arkliving.com",
  "google_rating": 3.8,
  "google_reviews_count": 1674,
  "notes": "Sheet type: Co-living. Chain or group",
  "service": "End-to-End Automation"
 }
]
